language: go
go:
  - 1.6
  - 1.7

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r -p --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --compilers=2
