language: go
go:
  - 1.7

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v github.com/wadey/gocovmerge
  - go get -v golang.org/x/tools/cover
  - export PATH=$PATH:$HOME/gopath/bin

script: ./test-with-coverage.sh
