// +build umbrella_testrunmain

// GENERATED by github.com/rosenhouse/umbrella/cmd/umbrella
// You may check this file into your source control.

package main

import (
	"flag"
	"os"
	"testing"
)

func TestRunWithUmbrellaCoverage(t *testing.T) {
	main()
	os.Stdout, _ = os.Create(os.DevNull)
}

func TestMain(m *testing.M) {
	prepCoverage()
	os.Exit(m.Run())
}

// path to save coverage data
// Build will override this at link-time, e.g.
//    go build -ldflags '-X yourprogram.coverProfilePath=/tmp/some/path'
var coverProfilePath = ""

func prepCoverage() {
	if coverProfilePath != "" {
		flag.Set("test.coverprofile", coverProfilePath)
	}
	flag.Set("test.run", "TestRunWithUmbrellaCoverage")
	origArgs := os.Args[1:]
	os.Args = append([]string{os.Args[0], "spacer"}, origArgs...)
	flag.Parse()
	os.Args = append([]string{os.Args[0]}, origArgs...)
}
